// DecompileDump.java — Ghidra headless post-script.
// Usage: analyzeHeadless <projdir> <proj> -import <binary> -postScript DecompileDump.java <outdir> -deleteProject -scriptPath <scriptdir>
// Chỉ tạo đúng 1 file <outdir>/_full.c: toàn bộ hàm đã lọc, đúng thứ tự địa chỉ.
import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileResults;
import ghidra.app.script.GhidraScript;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.FunctionIterator;
import java.io.File;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

public class DecompileDump extends GhidraScript {
    @Override
    public void run() throws Exception {
        String[] args = getScriptArgs();
        if (args.length < 1) {
            printerr("DecompileDump: missing output dir arg");
            return;
        }
        File outDir = new File(args[0]);
        outDir.mkdirs();

        DecompInterface decomp = new DecompInterface();
        decomp.openProgram(currentProgram);

        // Giữ lại (địa chỉ, tên, code) để dựng file tổng hợp đúng thứ tự gốc.
        List<String[]> ordered = new ArrayList<>();
        int count = 0, failed = 0, done = 0;
        FunctionIterator funcs = currentProgram.getFunctionManager().getFunctions(true);
        while (funcs.hasNext() && !monitor.isCancelled()) {
            Function f = funcs.next();
            // Bỏ hàm thừa: thunk trỏ sang import (stub PLT) và hàm ngoài chương trình.
            if (f.isThunk() || f.isExternal()) {
                continue;
            }
            String name = f.getName() + "@" + f.getEntryPoint().toString();
            DecompileResults res = decomp.decompileFunction(f, 60, monitor);
            if (res != null && res.decompileCompleted()) {
                String code = res.getDecompiledFunction().getC();
                // Bỏ chữ thừa: các dòng cảnh báo của Ghidra (kể cả thụt đầu dòng trong thân hàm).
                code = code.replaceAll("(?m)^[ \\t]*/\\* WARNING[^\\n]*\\*/[ \\t]*\\n?", "");
                // Bỏ hàm rỗng/stub: thân chỉ còn return hoặc trống.
                String body = code.replaceAll("(?s)^.*?\\{", "{").trim();
                if (body.matches("(?s)\\{\\s*(return\\s*[^;]*;)?\\s*\\}")) {
                    continue;
                }
                ordered.add(new String[]{f.getEntryPoint().toString(), name, code});
                count++;
            } else {
                failed++;
            }
            if ((++done % 200) == 0) println("DecompileDump: " + done + " functions...");
        }
        // File duy nhất: toàn bộ hàm sắp xếp theo địa chỉ (gần thứ tự bố cục gốc nhất).
        ordered.sort(Comparator.comparing(a -> a[0]));
        try (FileWriter w = new FileWriter(new File(outDir, "_full.c"))) {
            w.write("// FULL DECOMPILATION — " + currentProgram.getName() + "\n");
            w.write("// functions: " + count + " | sorted by entry address (original layout order)\n");
            w.write("// generated by Ghidra " + currentProgram.getLanguageID() + "\n\n");
            for (String[] e : ordered) {
                w.write("// ================= " + e[1] + " =================\n");
                w.write(e[2]);
                w.write("\n\n");
            }
        }
        println("DecompileDump done: decompiled=" + count + " failed=" + failed);
        decomp.dispose();
    }
}
