// DecompileDump.java — Ghidra headless post-script.
// Usage: analyzeHeadless <projdir> <proj> -import <binary> -postScript DecompileDump.java <outdir> -deleteProject -scriptPath <scriptdir>
// Dumps each function's decompiled C into <outdir>/<func>.c + _index.txt listing all functions.
import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileResults;
import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.Address;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.FunctionIterator;
import java.io.File;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

public class DecompileDump extends GhidraScript {
    @Override
    public void run() throws Exception {
        String[] args = getScriptArgs();
        if (args.length < 1) {
            printerr("DecompileDump: missing output dir arg");
            return;
        }
        File outDir = new File(args[0]);
        outDir.mkdirs();

        DecompInterface decomp = new DecompInterface();
        decomp.openProgram(currentProgram);

        StringBuilder index = new StringBuilder();
        // Giữ lại (địa chỉ, tên, code) để dựng file tổng hợp đúng thứ tự gốc.
        List<String[]> ordered = new ArrayList<>();
        int count = 0, failed = 0;
        FunctionIterator funcs = currentProgram.getFunctionManager().getFunctions(true);
        while (funcs.hasNext() && !monitor.isCancelled()) {
            Function f = funcs.next();
            // Bỏ hàm thừa: thunk trỏ sang import (stub PLT) và hàm ngoài chương trình.
            if (f.isThunk() || f.isExternal()) {
                continue;
            }
            String name = f.getName() + "@" + f.getEntryPoint().toString();
            DecompileResults res = decomp.decompileFunction(f, 60, monitor);
            if (res != null && res.decompileCompleted()) {
                String code = res.getDecompiledFunction().getC();
                // Bỏ chữ thừa: các dòng cảnh báo của Ghidra (kể cả thụt đầu dòng trong thân hàm).
                code = code.replaceAll("(?m)^[ \\t]*/\\* WARNING[^\\n]*\\*/[ \\t]*\\n?", "");
                // Bỏ hàm rỗng/stub: thân chỉ còn return hoặc trống.
                String body = code.replaceAll("(?s)^.*?\\{", "{").trim();
                if (body.matches("(?s)\\{\\s*(return\\s*[^;]*;)?\\s*\\}")) {
                    continue;
                }
                ordered.add(new String[]{f.getEntryPoint().toString(), name, code});
                String safe = f.getName().replaceAll("[^a-zA-Z0-9_.$-]", "_");
                File out = new File(outDir, safe + ".c");
                // Avoid collisions (overloads / same names).
                int dup = 1;
                while (out.exists()) {
                    out = new File(outDir, safe + "__" + (dup++) + ".c");
                }
                try (FileWriter w = new FileWriter(out)) {
                    w.write("// " + name + "\n// addr: " + f.getEntryPoint() + "\n\n");
                    w.write(code);
                }
                count++;
            } else {
                failed++;
            }
            index.append(f.getEntryPoint()).append("  ").append(name).append("\n");
            if ((count + failed) % 200 == 0) println("DecompileDump: " + (count + failed) + " functions...");
        }
        // File tổng hợp: toàn bộ hàm sắp xếp theo địa chỉ (gần thứ tự bố cục gốc nhất có thể).
        ordered.sort(Comparator.comparing(a -> a[0]));
        try (FileWriter w = new FileWriter(new File(outDir, "_full.c"))) {
            w.write("// FULL DECOMPILATION — " + currentProgram.getName() + "\n");
            w.write("// functions: " + count + " | sorted by entry address (original layout order)\n");
            w.write("// generated by Ghidra " + currentProgram.getLanguageID() + "\n\n");
            for (String[] e : ordered) {
                w.write("// ================= " + e[1] + " =================\n");
                w.write(e[2]);
                w.write("\n\n");
            }
        }
        try (FileWriter w = new FileWriter(new File(outDir, "_index.txt"))) {
            w.write("decompiled=" + count + " failed=" + failed + "\n\n");
            w.write(index.toString());
        }
        println("DecompileDump done: decompiled=" + count + " failed=" + failed);
        decomp.dispose();
    }
}
